config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }
  
  devise_scope :user do 
    patch "users/confirmation", to: "users/confirmations#confirm"
    get "users/thanks", to: "users/registrations#thanks"
    get "users/confirmation/complete", to: "users/confirmations#complete"
    get "profile/edit", to: "users/confirmations#edit"
    patch "profile/edit", to: "users/confirmations#update"
  end
  
  namespace :e_sal, :path => "e-sal" do
    get '/', to: 'homes#index'

    resources :programmings, path: "programming" do
      resources :programming_answers, path: "answer", except: [:index, :destroy] do
        collection do
          get '/list', to: 'programming_answers#list'
          get '/submit', to: 'programming_answers#submit'
        end
      end
    end

    resources :tutorials do
      collection do
        get '/list', to: 'tutorials#list'
        get '/list/:main_category' => 'tutorials#main_category_list'
        get '/list/:main_category/:original_category' => 'tutorials#original_category_list'
        post '/photos', to: 'photos#create'
        post '/:id/edit/photos', to: 'photos#create'
        post '/preview/:id' => 'tutorials#preview'
        patch '/preview/:id' => 'tutorials#preview'
        get '/preview/:id' => 'tutorials#preview'
        post '/tutorial-like' => 'tutorial_likes#create'
        delete '/tutorial-like' => 'tutorial_likes#destroy'
        post '/tutorial-dislike' => 'tutorial_dislikes#create'
        delete '/tutorial-dislike' => 'tutorial_dislikes#destroy'
      end
      resources :comments
    end

    resources :original_categories
    resources :photos
  end

  get "/agreement", to: "home#agreement", as: :agreement
  root 'home#index'
  # どれにもroutingされなければ、404を表示する(なので下記のroutingより下には何も書いてはいけない)
  get '*path', controller: 'application', action: 'render_404'
end

app/views/layouts/common_partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    Copyright &copy; 2017 サービス名 All rights reserved.
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

app/views/layouts/common_partials/_header.html.erb
<div class="contents__header">
  <div class="contents__header-menu" id="js-header-menu">
    <i class="fa fa-cog gear" aria-hidden="true"></i>
  </div>

  <div class="header-menu-list" id="js-header-menu-list">
    <ul>
      <%= link_to profile_edit_path do %>
        <li><i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;&nbsp;Profile</li>
      <% end %>
      <%= link_to destroy_user_session_path, :method => :delete do %>
        <li><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;&nbsp;Sign Out</li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/common_partials/_header_stats.html.erb
  <div class="contents-top__stats-wrap">
    <div class="contents-top__stats">
      <span class="contents-top__stats-title"><i class="fa fa-user"></i> Total Users</span>
      <div class="contents-top__stats-count">1000</div>
      <span class="contents-top__stats-change"><i class="green">5%</i> up from last week</span>
    </div>
    
    <div class="contents-top__stats">
      <span class="contents-top__stats-title"><i class="fa fa-user"></i> Total Users</span>
      <div class="contents-top__stats-count">207</div>
      <span class="contents-top__stats-change"><i class="green">5%</i> up from last week</span>
    </div>
  
    <div class="contents-top__stats">
      <span class="contents-top__stats-title"><i class="fa fa-user"></i> Total Users</span>
      <div class="contents-top__stats-count">1300</div>
      <span class="contents-top__stats-change"><i class="green">5%</i> up from last week</span>
    </div>
    
    <div class="contents-top__stats">
      <span class="contents-top__stats-title"><i class="fa fa-user"></i> Total Users</span>
      <div class="contents-top__stats-count">10</div>
      <span class="contents-top__stats-change"><i class="green">5%</i> up from last week</span>
    </div>

    <div class="contents-top__stats">
      <span class="contents-top__stats-title"><i class="fa fa-user"></i> Total Users</span>
      <div class="contents-top__stats-count">508</div>
      <span class="contents-top__stats-change"><i class="green">5%</i> up from last week</span>
    </div>

    <div class="contents-top__stats">
      <span class="contents-top__stats-title"><i class="fa fa-user"></i> Total Users</span>
      <div class="contents-top__stats-count">7</div>
      <span class="contents-top__stats-change"><i class="green">5%</i> up from last week</span>
    </div>
  </div><!-- /contents-top__stats-wrap -->

app/views/layouts/common_partials/_sidebar.html.erb
<!-- left sidebar -->
<div class="sidebar">
  <div class="sidebar__wrap">
    <div class="profile clearfix">
      <div class="profile__pic">
        <img class="img-circle profile_img" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" width="80" height="80"/>
      </div>
      <div class="profile__info">
        <span>Welcome</span>
        <h2 class="profile__name"><%= User.find(current_user.id).user_name %>さん</h2>
      </div>
    </div>
  
    <br />
  
    <!-- sidebar menu -->
    <div class="sidebar__menu-wrap" class="main_menu_side hidden-print main_menu">
      <div class="sidebar__menu_section">
        <ul class="sidebar__menu">
          <li class="sidebar__items">
            <%= link_to e_sal_path do %>
              <div class="sidebar__item"><i class="fa fa-home" aria-hidden="true"></i><span class="sidebar__action">Home</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to e_sal_programmings_path do %>
              <div class="sidebar__item"><i class="fa fa-desktop" aria-hidden="true"></i><span class="sidebar__action">Solving Programming</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to e_sal_original_categories_path do %>
              <div class="sidebar__item"><i class="fa fa-list" aria-hidden="true"></i><span class="sidebar__action">My Category</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <%= link_to e_sal_tutorials_path do %>
              <div class="sidebar__item"><i class="fa fa-book fa-fw"></i><span class="sidebar__action">My Tutorial</span></div>
            <% end %>
          </li>
          <li class="sidebar__items">
            <div class="sidebar__item">
              <%= link_to list_e_sal_tutorials_path do %>
                <i class="fa fa-files-o"></i><span class="sidebar__action">Reading Tutorials</span>
              <% end %>
                <span class="fa fa-chevron-down sidebar__down-arrow" id="js-slider-button"></span>
            </div>
            <ul class="sidebar__tutorial" id="js-slider-menu">
              <% side_tutorial_list.each do |t| %>
                <li><i class="fa fa-circle" aria-hidden="true"></i></i>&nbsp;&nbsp;<%= link_to t.name,  {controller:"e_sal/tutorials", action:"main_category_list", main_category: t.name_url} %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <!-- /sidebar__menu -->
  </div>

  <br />

</div>
<!-- /sidebar -->