config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }
  
  devise_scope :user do 
    patch "users/confirmation", to: "users/confirmations#confirm"
    get "users/thanks", to: "users/registrations#thanks"
    get "users/confirmation/complete", to: "users/confirmations#complete"
    get "profile/edit", to: "users/confirmations#edit"
    patch "profile/edit", to: "users/confirmations#update"
  end
  
  namespace :e_sal, :path => "e-sal" do
    get '/', to: 'homes#index'

    resources :programmings, path: "programming" do
      resources :programming_answers, path: "answer", except: [:index, :destroy] do
        collection do
          get '/list', to: 'programming_answers#list'
          get '/submit', to: 'programming_answers#submit'
        end
      end
    end

    resources :tutorials do
      collection do
        get '/list', to: 'tutorials#list'
        get '/list/:main_category' => 'tutorials#main_category_list'
        get '/list/:main_category/:original_category' => 'tutorials#original_category_list'
        post '/photos', to: 'photos#create'
        post '/:id/edit/photos', to: 'photos#create'
        post '/preview/:id' => 'tutorials#preview'
        patch '/preview/:id' => 'tutorials#preview'
        get '/preview/:id' => 'tutorials#preview'
        post '/tutorial-like' => 'tutorial_likes#create'
        delete '/tutorial-like' => 'tutorial_likes#destroy'
        post '/tutorial-dislike' => 'tutorial_dislikes#create'
        delete '/tutorial-dislike' => 'tutorial_dislikes#destroy'
      end
      resources :comments
    end

    resources :original_categories
    resources :photos
  end

  get "/agreement", to: "home#agreement", as: :agreement
  root 'home#index'
  # どれにもroutingされなければ、404を表示する(なので下記のroutingより下には何も書いてはいけない)
  get '*path', controller: 'application', action: 'render_404'
end

app/models/e_sal.rb
module ESal
  def self.table_name_prefix
    'e_sal_'
  end
end

app/controllers/e_sal/base.rb
class ESal::Base < ApplicationController

  LIST_NUM_PER_PAGE = 10

  before_action :authenticate_user!

  def get_current_user_id
    current_user.id  
  end
end

app/controllers/e_sal/comments_controller.rb
class ESal::CommentsController < ESal::Base
  before_action :set_tutorial

  def create
    unless current_user
      flash[:alert] = "ログインしてください。"
      redirect_to root_path
    else
      @comment = @tutorial.comments.build(comment_params)
      @comment.user = current_user
      
      if @comment.save
        flash[:notice] = "コメントが投稿されました。"
        redirect_to e_sal_tutorial_path(@tutorial) and return
      else
        @comments = @tutorial.comments
        flash[:alert] = "コメント投稿に失敗しました。エラー内容はコメント記入欄の下のメッセージをご確認ください。"
        render "e_sal/tutorials/show" and return
      end
    end
  end
  
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
    
    def set_tutorial
      @tutorial = Tutorial.find(params[:tutorial_id])
    end
end

app/controllers/e_sal/homes_controller.rb
class ESal::HomesController < ESal::Base
  
  def index
    
    @timelines = PublicActivity::Activity.where(
      "trackable_type not in(?, ?)",
      "User",
      "ProgrammingAnswer"
      ).order(created_at: :desc).limit(10)
      
    @activities = PublicActivity::Activity.where(
      "owner_id = ? or recipient_id = ?",
      current_user.id, current_user.id,
      ).order(created_at: :desc).limit(10)
    
    @pie_course_types = User.get_pie_course_types
    
    @programming_answers = ProgrammingAnswer.has_draft(current_user.id)
    
    @tutorials = Tutorial.has_draft(current_user.id)
      
  end
end

app/controllers/e_sal/likes_controller.rb
class ESal::LikesController < ESal::Base

  def create
    if params[:tutorial_id].blank? || params[:user_id].blank?
      redirect_to e_sal_tutorial_path(id: params[:user_id])
      return
    end

    if Like.create(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  def destroy
  
  end
  
  private
    def likes_params
      params.fetch(:like, {}).permit(:tutorial_id, :user_id)
    end
end

app/controllers/e_sal/original_categories_controller.rb
class ESal::OriginalCategoriesController < ESal::Base
  before_action :set_original_category, only: [:show, :edit, :update, :destroy]

  def index
    # @original_categories = OriginalCategory.get_by_user_id(current_user.id).page(params[:page]).per(LIST_NUM_PER_PAGE)
    @original_categories = OriginalCategory.get_has_tutorial(current_user.id).page(params[:page]).per(LIST_NUM_PER_PAGE)
  end

  def new
    @original_category = OriginalCategory.new
    set_current_user_id
    get_all_main_categories
  end

  def edit
    get_all_main_categories
    has_tutorials
  end

  def create
    @original_category = OriginalCategory.new(original_category_params)

    respond_to do |format|
      if @original_category.save
        format.html { redirect_to action: :index, notice: "「#{@original_category.name}」カテゴリを作成しました。" }
      else
        get_all_main_categories
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @original_category.update(original_category_params)
        format.html { redirect_to action: :index, notice: "「#{@original_category.name}」カテゴリをアップデートしました。" }
      else
        get_all_main_categories
        has_tutorials
        format.html { render :edit }
      end
    end
  end

  def destroy
    deleted_category = @original_category.name
    if @original_category.destroy
      message = "「#{deleted_category}」カテゴリを削除しました。"
    else
      message = "「#{deleted_category}」カテゴリの削除に失敗しました。"
    end

    respond_to do |format|
      format.html { redirect_to action: :index, notice: message }
    end
  end

  private
    def set_original_category
      @original_category = OriginalCategory.find(params[:id])
    end

    def original_category_params
      params.fetch(:original_category, {}).permit(:name, :name_url, :main_category_id, :user_id, :created_at)
    end

    def set_current_user_id
      @original_category.user_id = get_current_user_id
    end
    
    def get_all_main_categories
      @main_categories = MainCategory.all_ids_and_name
    end

    # 既にチュートリアルにオリジナルカテゴリが使用されていたら編集できないようにする。
    def has_tutorials
      @has_tutorials = Tutorial.has_tutorials?(@original_category.id)
    end
end

app/controllers/e_sal/photos_controller.rb
class ESal::PhotosController < ApplicationController

  def create
    if photo_params
      photos = []
      params[:images].each_with_index do |image, i|
        photos[i] = Photo.create(image: image, user_id: params[:user_id])
      end
      render json: { photos: photos }, :status => 200
    end
  end

  private
    def photo_params
      params.permit(:id, :images, :user_id)
    end
end

app/controllers/e_sal/programming_answers_controller.rb
class ESal::ProgrammingAnswersController < ESal::Base
  before_action :find_programming
  before_action :set_programming_answer, only: [:show, :edit, :update]
  before_action :set_status, only: [:create, :update]

  def show
    unless ProgrammingAnswer.has_answered?(current_user.id, @programming.id)
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "回答済みの場合のみ他の人の回答を閲覧できます"}
      end
      return
    end
    
    @user = User.find_by(id: @programming_answer.user_id)
  end

  def new
    @programming_answer = @programming.programming_answers.new
  end

  def create

    @programming_answer = @programming.programming_answers.new(programming_answer_params)
    
    @programming_answer.user_id = current_user.id
    
    if params[:draft]
      status = 'draft'
    else
      status = 'answered'
    end
    @programming_answer.answer_status = status
    
    respond_to do |format|
      if @programming_answer.save
        @programming_answer.create_activity :create, owner: current_user, params: {
          link_url: e_sal_programming_programming_answer_path(@programming_answer.programming_id, @programming_answer.id),
          title: @programming.title} if params[:answered]
        format.html {redirect_to e_sal_programmings_path({status: status}), notice: "保存が完了しました"}
      else
        format.html {render :new}
      end
    end
  end

  def edit
    unless chk_current_user
      respond_to do |format|
        format.html {redirect_to e_sal_programmings_path, alert: "他の人の回答は編集できません"}
      end
      return
    end
  end

  def update

    @programming_answer.attributes = programming_answer_params

    if params[:draft]
      status = 'draft'
    else
      status = 'answered'
    end
    @programming_answer.answer_status = status

    respond_to do |format|
      if @programming_answer.save
        @programming_answer.create_activity :create, owner: current_user, params: {
          link_url: e_sal_programming_programming_answer_path(@programming_answer.programming_id, @programming_answer.id),
          title: @programming.title} if params[:answered]
        format.html {redirect_to e_sal_programming_programming_answer_path, notice: "保存が完了しました"}
      else
        format.html {render :edit}
      end
    end
  end

  # get list others
  def list
    
    unless ProgrammingAnswer.has_answered?(current_user.id, @programming.id)
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "回答済みの場合のみ他の人の回答を閲覧できます"}
      end
      return
    end
    
    @programming_answers = ProgrammingAnswer.others(current_user.id, @programming.id).page(params[:page]).per(LIST_NUM_PER_PAGE)
    
  end
  
  def submit
    
    require 'systemu'
    
    lang_map = {"perl": "pl", "php": "php", "python": "py", "ruby": "rb"}
    
    chk_dir = Rails.root.join("tmp", "programming", "submit")

    unless chk_dir.exist?
      system("mkdir -p #{chk_dir.to_s}")
    end

    submit_dir = chk_dir.to_s

    lang = params[:lang]
    code = params[:code]
    f_time = Time.zone.now.strftime("%Y%m%d%H%S%M%L")
    
    file_name = "#{submit_dir}/#{f_time}.#{lang_map[lang.to_sym]}"
    
    File.open(file_name, "w") do |file|
      file.puts("# -*- coding: utf-8 -*-") if lang == "python"
      file.puts(code)
    end

    command = "#{lang} #{file_name}"
    
    out = ""
    err = ""

    systemu command, out: out, err: err
    
    unless err == ""
      out = err
      out = out.gsub(file_name, "")
    end
    
    data = {stdout: out}
    
    File.delete(file_name)
    
    respond_to do |format|
      format.json {render json: data}
    end
  end
  
  private
  
  def chk_current_user
    @programming_answer.user_id == current_user.id
  end
  
  def find_programming
    @programming = Programming.find(params[:programming_id])
  end
  
  def programming_answer_params
    params.require(:programming_answer).permit(:programming_language, :tab_size, :answer_code,
                  :answer_result, :answer_status, :programming_id)
  end
  
  def set_programming_answer
    @programming_answer = @programming.programming_answers.find_by(id: params[:id])
  end
  
  def set_status
    params[:programming_answer][:answer_status] = ProgrammingAnswer.answer_statuses[params[:programming_answer][:answer_status]]
  end
  
end

app/controllers/e_sal/programmings_controller.rb
class ESal::ProgrammingsController < ESal::Base
  before_action :set_programming, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:new, :create]
  before_action :get_programming_answer, only: [:edit, :destroy]
  
  def index
    status = "all"
    if params[:status]
      status = params[:status]
    end
    
    @status = status
    @programmings = Programming.get_list(current_user.id, status).page(params[:page]).per(LIST_NUM_PER_PAGE)
    
  end

  def show
    @programming_answer = @programming.programming_answers.find_by(user_id: current_user.id)
    
    if @programming.user_id == current_user.id && !Programming.has_answers(@programming.id)
      @programming_own = true
    else
      @programming_own = false
    end
  end
  
  def new
    @programming = @user.programmings.build()
  end
  
  def create
    @programming = @user.programmings.build(programming_params)

    @programming.confirmed = false if params[:commit] == "戻る"

    if @programming.save
      @programming.create_activity :create, owner: current_user, params: {
        link_url: e_sal_programming_path(@programming.id),
        title: @programming.title}
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), notice: "登録が完了しました"}
      end
    else
      respond_to do |format|
        format.html {render action: 'new'}
      end
    end
  end
  
  def edit
    unless @programming_answer.nil?
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "既に回答が投稿されているため、編集できません"}
      end
      return
    end
  end
  
  def update

    @user = User.find(@programming.user_id)
    @programming.attributes = programming_params
    
    @programming.confirmed = false if params[:commit] == "戻る"

    if @programming.save
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), notice: "更新が完了しました"}
      end
    else
      respond_to do |format|
        format.html {render 'edit'}
      end
    end
  end
  
  def destroy
    unless @programming_answer.nil?
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "既に回答が投稿されているため削除できません"}
      end
      return
    end
    
    if @programming.destroy
      respond_to do |format|
        format.html {redirect_to e_sal_programmings_path(status: 'own'), notice: "削除が完了しました"}
      end
    else
      respond_to do |format|
        format.html {render 'show'}
      end
    end
  end
  
  private
  
  def find_user
    @user = User.find(current_user.id)
  end
  
  def get_programming_answer
    @programming_answer = @programming.programming_answers.find_by(programming_id: @programming.id)
  end
  
  def set_programming
    @programming = Programming.find(params[:id])
  end
  
  def programming_params
    params.require(:programming).permit(
      :title, :question_desc, :correct_answer, :confirmed)
  end
end

app/controllers/e_sal/tutorial_dislikes_controller.rb
class ESal::TutorialDislikesController < ESal::Base
  before_action :dislikes_params,
                :find_dislike, only: [:destroy]

  def create
    return if params[:tutorial_id].blank? || params[:user_id].blank?

    if TutorialDislike.create(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  def destroy
    if @dislike.destroy
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  private
    def dislikes_params
      params.fetch(:like, {}).permit(:tutorial_id, :user_id)
    end
    
    def find_dislike
      @dislike = TutorialDislike.find_by(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
    end
end

app/controllers/e_sal/tutorial_likes_controller.rb
class ESal::TutorialLikesController < ESal::Base
  before_action :likes_params,
                :find_like, only: [:destroy]
  def create
    return if params[:tutorial_id].blank? || params[:user_id].blank?

    if TutorialLike.create(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  def destroy
    if @like.destroy
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  private
    def likes_params
      params.fetch(:like, {}).permit(:tutorial_id, :user_id)
    end
    
    def find_like
      @like = TutorialLike.find_by(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
    end
end

app/helpers/e_sal/comments_helper.rb
module ESal::CommentsHelper
end

app/helpers/e_sal/homes_helper.rb
module ESal::HomesHelper
end

app/helpers/e_sal/original_categories_helper.rb
module ESal::OriginalCategoriesHelper
end

app/helpers/e_sal/photos_helper.rb
module ESal::PhotosHelper
end

app/helpers/e_sal/programming_answers_helper.rb
module ESal::ProgrammingAnswersHelper
end

app/helpers/e_sal/programmings_helper.rb
module ESal::ProgrammingsHelper
end

app/helpers/e_sal/tutorials_helper.rb
module ESal::TutorialsHelper
  def markdown(text)
    unless @markdown
      renderer = Redcarpet::Render::HTML.new(filter_html: true)
      options = {
          autolink: true,
          space_after_headers: true,
          no_intra_emphasis: true,
          fenced_code_blocks: true,
          tables: true,
          hard_wrap: true,
          xhtml: true,
          lax_html_blocks: true,
          strikethrough: true
      }
      @markdown = Redcarpet::Markdown.new(renderer, options)
    end

    @markdown.render(text).html_safe
  end
  
  def persisted_comments(comments)
    comments.reject{ |comment| comment.new_record? }
  end
end

app/views/e_sal/tutorials/_form.html.erb
<div class="tutorial-area">
  <div class="contents-wrap">
    <div class="x_panel">
      <div class="x_title">
        <h2 class="tutorial-edit-title">チュートリアル編集フォーム</h2>
        <div class="clearfix"></div>
      </div>
        <div class="x_content">
          <%= bootstrap_form_for([:e_sal, @tutorial], layout: :horizontal) do |f| %>
            <div class="tutorial-edit-left-area">
              <%= f.hidden_field :id %>
              <%= f.hidden_field :user_id %>

              <div class="form-group">
                <div class="tutorial-edit-left-area__title-area">
                  <div class="tutorial-edit-left-area__title"><span>タイトル</span></div>
                  <div class="tutorial-edit-left-area__title-count"><span>タイトルの文字数:</span><span id="js-tutorial-title-count">0</span></div>
                </div>
                <%= f.text_field :title, hide_label: true, class: "js-disabled-enter", id: "js-tutorial-title" %>
              </div>
  
              <div class="form-group">
                <div class="image-upload-area">
                  <div class="image-upload-area__drop-zone" id="js-image-drop-zone">Please drop files here...</div>
                </div>
              </div>

              <div class="form-group">
                <div class="tutorial-edit-left-area__tutorial-body-area">
                  <div class="tutorial-edit-left-area__tutorial-body"><span>チュートリアル本文</span></div>
                  <div class="tutorial-edit-left-area__tutorial-body-count"><span>チュートリアル本文の文字数:</span><span id="js-tutorial-body-count">0</span></div>
                </div>
                <%= f.fields_for :tutorial_content, @tutorial.tutorial_content || TutorialContent.new do |t| %>
                  <%= t.hidden_field :id %>
                  <%= t.text_area :body, hide_label: "true", rows: "20", id: "js-tutorial-body" %>
                <% end %>
                <div class="tutorial-edit-left-area__body-error"><%= f.errors_on :body, hide_attribute_name: true %></div>
              </div>
            </div><!-- end of tutorial-edit-left-area -->
      
            <div class="tutorial-edit-right-area">
              <div class="form-group">
                <span>My Category</span>
                <%= f.select :original_category_id, @original_categories.map{|t| [t.name, t.id]}, { prompt: "選択してください", hide_label: true }, class: "" %>
              </div>

              <div class="form-group">
                <span>公開 / 非公開 (下書きは非公開を選択)</span>
                <%= f.select :status, Tutorial::Status.publish_select_options, { selected: @tutorial.check_status, hide_label: true }, class: "" %>
              </div>

              <div class="form-group">
                <span>コメント許可</span>
                <%= f.select :comment_enable_flg, Tutorial::CommentPermission.comment_select_options, { selected: @tutorial.check_comment_permission, hide_label: true }, class: "" %>
              </div>

              <div class="form-group">
                <span>更新日</span>
                <%= f.text_field :datetime_for_display, data: { :date_format => 'YYYY/MM/DD hh:mm' }, hide_label: true, class: 'js-disabled-enter date-fields', id: "datetimepicker4",  placeholder: 'クリックして下さい' %>
              </div>

              <%= f.submit "更新する", id: "js-update-button" %>
              <%= f.submit "プレビュー", name: "preview", id: "js-preview-button" %>
            </div><!-- end of tutorial-edit-right-area -->
          <% end %>
      </div><!-- end of x_content -->
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function () {
    $('#datetimepicker4').datetimepicker();
  });
</script>

app/views/e_sal/tutorials/_list.html.erb
<div class="tutorial-area">
  <div class="contents-wrap">
    <%= render partial: 'layouts/common_partials/header_stats' %>
  
      <h1 class="list-title"><%= @list_title %>のチュートリアル一覧</h1>
      <div class="paging"><%= paginate(@tutorials) %></div>
      <% @tutorials.each do |t| %>
        <div class="tutorial-wrap">
          <div class="tutorial-material">
            <i class="tutorial-material__pin"></i>
            <div class="tutorial-material__note tutorial-material__background">
              <div class="tutorial-material__title"><%= t.title %></div>
              <div class="tutorial-material__image-body-area">
                <div class="tutorial-material__image"><%= image_tag("main_categories/#{t.main_category.name_url}.png") %></div>
                <div class="tutorial-material__body"><%= truncate(t.tutorial_content.body, length: 80) %></div>
              </div>
              <%= link_to url_for(controller: :tutorials, action: :show, id: t.id) do %>
                <div class="tutorial-material__read-more">このチュートリアルを読む</div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
  <!--左上が折れてるバージョン
    <div class="tutorial-material tutorial-corner-fold">
      <h2>タイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトル</h2>
      <p class="tutorial-material__contents">問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題問題</p>
      <p class="tutorial-material__detail-link">このチュートリアルを読む</p>
    </div>
  -->
    <div class="paging"><%= paginate(@tutorials) %></div>
  </div>
</div>

app/views/e_sal/tutorials/_tutorial.html.erb
<div class="tutorial-area">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= h(flash[:notice]) %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= h(flash[:alert]) %>
    </div>
  <% end %>
  <div class="contents-wrap">
    <div class="tutorial-note">
      <i class="tutorial-note__pin"></i>
      <h2 class="tutorial-note__title"><%= @tutorial.title %></h2>
      <div class="tutorial-note__date"><%= l @tutorial.datetime_for_display, format: :date %></div>
      <div class="tutorial-note__main-sentence">
        <% if @preview.present? %>
          <%= markdown @body %>
        <% else %>
          <%= markdown @tutorial.tutorial_content.body %>
        <% end %>
      </div>
    </div>
    
    <% if @preview.blank? %> 
  　　<%= link_to "#{@tutorial_list_title}のチュートリアル一覧はこちら", controller: "e_sal/tutorials", action: "original_category_list", main_category: @main_category, original_category: @original_category %>

      <div class="evaluation-button">
        <p>このチュートリアルはあなたにとってお役に立ちましたか？</p>
        <button class="evaluation-button__like-button" id="js-like-button" data-like="on">
          <i class="evaluation-button__fa fa fa-thumbs-o-up" aria-hidden="true"></i> Like
        </button>
        <span class="evaluation-button__like-numbers" id="js-like-numbers"><%= @number_of_likes %></span>
        <button class="evaluation-button__dislike-button" id="js-dislike-button" data-dislike="on">
          <i class="fa fa fa-thumbs-o-down" aria-hidden="true"></i> Dislike
        </button>
        <span class="evaluation-button__like-numbers" id="js-dislike-numbers"><%= @number_of_dislikes %></span>    
      </div>
  
      <hr>
<% if @tutorial.comment_enable_flg == 2 %>
      <div class="comment-area">
        <div class="comment-area__character-count">
          <p>最大200文字まで<span class="comment-area__current-character-num-area">現在の文字数：<span class="comment-area__current-character-num" id="js-comment-count">0</span></span></p>
        </div>
        <%= form_for [:e_sal, @tutorial, @comment], :html => {class: "form-horizontal", role: "form"} do |f| %>
          <div class='form-group'>
            <div class='control-label col-md-2'>
              <%= f.label :body, 'Comment' %> 
            </div>
            <div class='col-md-10'>
              <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Your comment', id: "js-comment-body" %> 
            </div>
          </div>
    
          <div class='form-group'>
            <div class='col-md-offset-2 col-md-10'>
              <%= f.submit "Add Comment", class: 'btn btn-primary btn-lg pull-right' %> 
            </div>
          </div>

          <% if @comment.errors.any? %>
            <div class="panel panel-danger col-md-offset-1">
              <div class="panel-heading">
                <div class="panel-body"> 
                  <ul>
                    <li> <%= @comment.errors.messages[:body][0] %> </li>
                  </ul>
                </div>
              </div><!-- /panel-heading --> 
            </div><!-- /panel panel-danger col-md-offset-1 -->
          <% end %>
        <% end %>
      </div>
  
      <div class='comment-history'> 
        <h2>Comment History</h2>
        <div class="col-md-12">
        <% if @tutorial.comments.any? %>
          <% persisted_comments(@comments).each do |comment| %> 
            <div class="comment-body">
              <%= comment.body %> 
            </div>
            <div class="comment-time">
              <%= time_ago_in_words(comment.created_at) %>前 by <%= comment.user.user_name %>
            </div>
            <hr>
          <% end %>
        <% else %>
          <p>表示するコメントはありません。</p>
        <% end %> 
      </div>
    <% end %>
  <% end %>
  </div>
</div>
<div style="display: none;" id="js-tutorial-id"><%= @tutorial.id %></div>
<div style="display: none;" id="js-user-id"><%= @current_login_user_id %></div>
<div style="display: none;" id="js-like-tutorial"><%= @press_like_button %></div>
<div style="display: none;" id="js-dislike-tutorial"><%= @press_dislike_button %></div>

app/views/e_sal/tutorials/edit.html.erb
<%= render 'form' %>

app/views/e_sal/tutorials/index.html.erb
<div class="tutorial-area">
  <div class="contents-wrap">
    <%= render partial: 'layouts/common_partials/header_stats' %>
  
    <p id="notice"><%= notice %></p>
  
    <%= link_to new_e_sal_tutorial_path  do %>
      <button type="button" class="btn btn-primary new-tutorial-button">チュートリアルの新規作成</button>
    <% end %>
  
    <section class="content-header">
      <div class="box-body">
        <div class="col-sm-12">
          <table class="table">
            <thead>
              <tr>
                <th>タイトル</th>
                <th>My Category / Main Category</th>
                <th>公開/非公開</th>              
                <th>コメント</th>
              </tr>            
            </thead>
            <tbody>
              <% @tutorials.each do |t| %>
                <tr>
                  <td><%= link_to t.title, url_for(controller: :tutorials, action: :edit, id: t.id)  %></td>
                  <% if t.original_category.present? && t.original_category.main_category.present? %>
                    <td><%= "#{t.original_category.name} / #{t.original_category.main_category.name}" %></td>
                  <% else %>
                    <td>設定されていません</td>
                  <% end %>
                  <td><%= t.status_for_display %></td>                
                  <td><%= t.comment_permission_for_display %></td>
                  <td>
                    <%= link_to '削除', url_for(controller: :tutorials, action: :destroy, id: t.id), method: :DELETE, data: {confirm: "チュートリアル「#{t.title}」を本当に削除しますか？"}  %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </section>
    <div class="paging"><%= paginate(@tutorials) %></div>
  </div>
</div>

app/views/e_sal/tutorials/list.html.erb
<%= render 'list' %>

app/views/e_sal/tutorials/main_category_list.html.erb
<%= render 'list' %>

app/views/e_sal/tutorials/new.html.erb
<%= render 'form' %>

app/views/e_sal/tutorials/original_category_list.html.erb
<%= render 'list' %>

app/views/e_sal/tutorials/preview.html.erb
<%= render 'tutorial' %>

app/views/e_sal/tutorials/show.html.erb
<% if flash[:alert] %>
  <%= render 'e_sal/tutorials/tutorial' %>
<% else %>
  <%= render 'tutorial' %>
<% end %>