config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }
  
  devise_scope :user do 
    patch "users/confirmation", to: "users/confirmations#confirm"
    get "users/thanks", to: "users/registrations#thanks"
    get "users/confirmation/complete", to: "users/confirmations#complete"
    get "profile/edit", to: "users/confirmations#edit"
    patch "profile/edit", to: "users/confirmations#update"
  end
  
  namespace :e_sal, :path => "e-sal" do
    get '/', to: 'homes#index'

    resources :programmings, path: "programming" do
      resources :programming_answers, path: "answer", except: [:index, :destroy] do
        collection do
          get '/list', to: 'programming_answers#list'
          get '/submit', to: 'programming_answers#submit'
        end
      end
    end

    resources :tutorials do
      collection do
        get '/list', to: 'tutorials#list'
        get '/list/:main_category' => 'tutorials#main_category_list'
        get '/list/:main_category/:original_category' => 'tutorials#original_category_list'
        post '/photos', to: 'photos#create'
        post '/:id/edit/photos', to: 'photos#create'
        post '/preview/:id' => 'tutorials#preview'
        patch '/preview/:id' => 'tutorials#preview'
        get '/preview/:id' => 'tutorials#preview'
        post '/tutorial-like' => 'tutorial_likes#create'
        delete '/tutorial-like' => 'tutorial_likes#destroy'
        post '/tutorial-dislike' => 'tutorial_dislikes#create'
        delete '/tutorial-dislike' => 'tutorial_dislikes#destroy'
      end
      resources :comments
    end

    resources :original_categories
    resources :photos
  end

  get "/agreement", to: "home#agreement", as: :agreement
  root 'home#index'
  # どれにもroutingされなければ、404を表示する(なので下記のroutingより下には何も書いてはいけない)
  get '*path', controller: 'application', action: 'render_404'
end

app/models/e_sal.rb
module ESal
  def self.table_name_prefix
    'e_sal_'
  end
end

app/controllers/e_sal/base.rb
class ESal::Base < ApplicationController

  LIST_NUM_PER_PAGE = 10

  before_action :authenticate_user!

  def get_current_user_id
    current_user.id  
  end
end

app/controllers/e_sal/comments_controller.rb
class ESal::CommentsController < ESal::Base
  before_action :set_tutorial

  def create
    unless current_user
      flash[:alert] = "ログインしてください。"
      redirect_to root_path
    else
      @comment = @tutorial.comments.build(comment_params)
      @comment.user = current_user
      
      if @comment.save
        flash[:notice] = "コメントが投稿されました。"
        redirect_to e_sal_tutorial_path(@tutorial) and return
      else
        @comments = @tutorial.comments
        flash[:alert] = "コメント投稿に失敗しました。エラー内容はコメント記入欄の下のメッセージをご確認ください。"
        render "e_sal/tutorials/show" and return
      end
    end
  end
  
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
    
    def set_tutorial
      @tutorial = Tutorial.find(params[:tutorial_id])
    end
end

app/controllers/e_sal/homes_controller.rb
class ESal::HomesController < ESal::Base
  
  def index
    
    @timelines = PublicActivity::Activity.where(
      "trackable_type not in(?, ?)",
      "User",
      "ProgrammingAnswer"
      ).order(created_at: :desc).limit(10)
      
    @activities = PublicActivity::Activity.where(
      "owner_id = ? or recipient_id = ?",
      current_user.id, current_user.id,
      ).order(created_at: :desc).limit(10)
    
    @pie_course_types = User.get_pie_course_types
    
    @programming_answers = ProgrammingAnswer.has_draft(current_user.id)
    
    @tutorials = Tutorial.has_draft(current_user.id)
      
  end
end

app/controllers/e_sal/likes_controller.rb
class ESal::LikesController < ESal::Base

  def create
    if params[:tutorial_id].blank? || params[:user_id].blank?
      redirect_to e_sal_tutorial_path(id: params[:user_id])
      return
    end

    if Like.create(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  def destroy
  
  end
  
  private
    def likes_params
      params.fetch(:like, {}).permit(:tutorial_id, :user_id)
    end
end

app/controllers/e_sal/original_categories_controller.rb
class ESal::OriginalCategoriesController < ESal::Base
  before_action :set_original_category, only: [:show, :edit, :update, :destroy]

  def index
    # @original_categories = OriginalCategory.get_by_user_id(current_user.id).page(params[:page]).per(LIST_NUM_PER_PAGE)
    @original_categories = OriginalCategory.get_has_tutorial(current_user.id).page(params[:page]).per(LIST_NUM_PER_PAGE)
  end

  def new
    @original_category = OriginalCategory.new
    set_current_user_id
    get_all_main_categories
  end

  def edit
    get_all_main_categories
    has_tutorials
  end

  def create
    @original_category = OriginalCategory.new(original_category_params)

    respond_to do |format|
      if @original_category.save
        format.html { redirect_to action: :index, notice: "「#{@original_category.name}」カテゴリを作成しました。" }
      else
        get_all_main_categories
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @original_category.update(original_category_params)
        format.html { redirect_to action: :index, notice: "「#{@original_category.name}」カテゴリをアップデートしました。" }
      else
        get_all_main_categories
        has_tutorials
        format.html { render :edit }
      end
    end
  end

  def destroy
    deleted_category = @original_category.name
    if @original_category.destroy
      message = "「#{deleted_category}」カテゴリを削除しました。"
    else
      message = "「#{deleted_category}」カテゴリの削除に失敗しました。"
    end

    respond_to do |format|
      format.html { redirect_to action: :index, notice: message }
    end
  end

  private
    def set_original_category
      @original_category = OriginalCategory.find(params[:id])
    end

    def original_category_params
      params.fetch(:original_category, {}).permit(:name, :name_url, :main_category_id, :user_id, :created_at)
    end

    def set_current_user_id
      @original_category.user_id = get_current_user_id
    end
    
    def get_all_main_categories
      @main_categories = MainCategory.all_ids_and_name
    end

    # 既にチュートリアルにオリジナルカテゴリが使用されていたら編集できないようにする。
    def has_tutorials
      @has_tutorials = Tutorial.has_tutorials?(@original_category.id)
    end
end

app/controllers/e_sal/photos_controller.rb
class ESal::PhotosController < ApplicationController

  def create
    if photo_params
      photos = []
      params[:images].each_with_index do |image, i|
        photos[i] = Photo.create(image: image, user_id: params[:user_id])
      end
      render json: { photos: photos }, :status => 200
    end
  end

  private
    def photo_params
      params.permit(:id, :images, :user_id)
    end
end

app/controllers/e_sal/programming_answers_controller.rb
class ESal::ProgrammingAnswersController < ESal::Base
  before_action :find_programming
  before_action :set_programming_answer, only: [:show, :edit, :update]
  before_action :set_status, only: [:create, :update]

  def show
    unless ProgrammingAnswer.has_answered?(current_user.id, @programming.id)
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "回答済みの場合のみ他の人の回答を閲覧できます"}
      end
      return
    end
    
    @user = User.find_by(id: @programming_answer.user_id)
  end

  def new
    @programming_answer = @programming.programming_answers.new
  end

  def create

    @programming_answer = @programming.programming_answers.new(programming_answer_params)
    
    @programming_answer.user_id = current_user.id
    
    if params[:draft]
      status = 'draft'
    else
      status = 'answered'
    end
    @programming_answer.answer_status = status
    
    respond_to do |format|
      if @programming_answer.save
        @programming_answer.create_activity :create, owner: current_user, params: {
          link_url: e_sal_programming_programming_answer_path(@programming_answer.programming_id, @programming_answer.id),
          title: @programming.title} if params[:answered]
        format.html {redirect_to e_sal_programmings_path({status: status}), notice: "保存が完了しました"}
      else
        format.html {render :new}
      end
    end
  end

  def edit
    unless chk_current_user
      respond_to do |format|
        format.html {redirect_to e_sal_programmings_path, alert: "他の人の回答は編集できません"}
      end
      return
    end
  end

  def update

    @programming_answer.attributes = programming_answer_params

    if params[:draft]
      status = 'draft'
    else
      status = 'answered'
    end
    @programming_answer.answer_status = status

    respond_to do |format|
      if @programming_answer.save
        @programming_answer.create_activity :create, owner: current_user, params: {
          link_url: e_sal_programming_programming_answer_path(@programming_answer.programming_id, @programming_answer.id),
          title: @programming.title} if params[:answered]
        format.html {redirect_to e_sal_programming_programming_answer_path, notice: "保存が完了しました"}
      else
        format.html {render :edit}
      end
    end
  end

  # get list others
  def list
    
    unless ProgrammingAnswer.has_answered?(current_user.id, @programming.id)
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "回答済みの場合のみ他の人の回答を閲覧できます"}
      end
      return
    end
    
    @programming_answers = ProgrammingAnswer.others(current_user.id, @programming.id).page(params[:page]).per(LIST_NUM_PER_PAGE)
    
  end
  
  def submit
    
    require 'systemu'
    
    lang_map = {"perl": "pl", "php": "php", "python": "py", "ruby": "rb"}
    
    chk_dir = Rails.root.join("tmp", "programming", "submit")

    unless chk_dir.exist?
      system("mkdir -p #{chk_dir.to_s}")
    end

    submit_dir = chk_dir.to_s

    lang = params[:lang]
    code = params[:code]
    f_time = Time.zone.now.strftime("%Y%m%d%H%S%M%L")
    
    file_name = "#{submit_dir}/#{f_time}.#{lang_map[lang.to_sym]}"
    
    File.open(file_name, "w") do |file|
      file.puts("# -*- coding: utf-8 -*-") if lang == "python"
      file.puts(code)
    end

    command = "#{lang} #{file_name}"
    
    out = ""
    err = ""

    systemu command, out: out, err: err
    
    unless err == ""
      out = err
      out = out.gsub(file_name, "")
    end
    
    data = {stdout: out}
    
    File.delete(file_name)
    
    respond_to do |format|
      format.json {render json: data}
    end
  end
  
  private
  
  def chk_current_user
    @programming_answer.user_id == current_user.id
  end
  
  def find_programming
    @programming = Programming.find(params[:programming_id])
  end
  
  def programming_answer_params
    params.require(:programming_answer).permit(:programming_language, :tab_size, :answer_code,
                  :answer_result, :answer_status, :programming_id)
  end
  
  def set_programming_answer
    @programming_answer = @programming.programming_answers.find_by(id: params[:id])
  end
  
  def set_status
    params[:programming_answer][:answer_status] = ProgrammingAnswer.answer_statuses[params[:programming_answer][:answer_status]]
  end
  
end

app/controllers/e_sal/programmings_controller.rb
class ESal::ProgrammingsController < ESal::Base
  before_action :set_programming, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:new, :create]
  before_action :get_programming_answer, only: [:edit, :destroy]
  
  def index
    status = "all"
    if params[:status]
      status = params[:status]
    end
    
    @status = status
    @programmings = Programming.get_list(current_user.id, status).page(params[:page]).per(LIST_NUM_PER_PAGE)
    
  end

  def show
    @programming_answer = @programming.programming_answers.find_by(user_id: current_user.id)
    
    if @programming.user_id == current_user.id && !Programming.has_answers(@programming.id)
      @programming_own = true
    else
      @programming_own = false
    end
  end
  
  def new
    @programming = @user.programmings.build()
  end
  
  def create
    @programming = @user.programmings.build(programming_params)

    @programming.confirmed = false if params[:commit] == "戻る"

    if @programming.save
      @programming.create_activity :create, owner: current_user, params: {
        link_url: e_sal_programming_path(@programming.id),
        title: @programming.title}
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), notice: "登録が完了しました"}
      end
    else
      respond_to do |format|
        format.html {render action: 'new'}
      end
    end
  end
  
  def edit
    unless @programming_answer.nil?
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "既に回答が投稿されているため、編集できません"}
      end
      return
    end
  end
  
  def update

    @user = User.find(@programming.user_id)
    @programming.attributes = programming_params
    
    @programming.confirmed = false if params[:commit] == "戻る"

    if @programming.save
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), notice: "更新が完了しました"}
      end
    else
      respond_to do |format|
        format.html {render 'edit'}
      end
    end
  end
  
  def destroy
    unless @programming_answer.nil?
      respond_to do |format|
        format.html {redirect_to e_sal_programming_path(@programming.id), alert: "既に回答が投稿されているため削除できません"}
      end
      return
    end
    
    if @programming.destroy
      respond_to do |format|
        format.html {redirect_to e_sal_programmings_path(status: 'own'), notice: "削除が完了しました"}
      end
    else
      respond_to do |format|
        format.html {render 'show'}
      end
    end
  end
  
  private
  
  def find_user
    @user = User.find(current_user.id)
  end
  
  def get_programming_answer
    @programming_answer = @programming.programming_answers.find_by(programming_id: @programming.id)
  end
  
  def set_programming
    @programming = Programming.find(params[:id])
  end
  
  def programming_params
    params.require(:programming).permit(
      :title, :question_desc, :correct_answer, :confirmed)
  end
end

app/controllers/e_sal/tutorial_dislikes_controller.rb
class ESal::TutorialDislikesController < ESal::Base
  before_action :dislikes_params,
                :find_dislike, only: [:destroy]

  def create
    return if params[:tutorial_id].blank? || params[:user_id].blank?

    if TutorialDislike.create(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  def destroy
    if @dislike.destroy
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  private
    def dislikes_params
      params.fetch(:like, {}).permit(:tutorial_id, :user_id)
    end
    
    def find_dislike
      @dislike = TutorialDislike.find_by(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
    end
end

app/controllers/e_sal/tutorial_likes_controller.rb
class ESal::TutorialLikesController < ESal::Base
  before_action :likes_params,
                :find_like, only: [:destroy]
  def create
    return if params[:tutorial_id].blank? || params[:user_id].blank?

    if TutorialLike.create(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  def destroy
    if @like.destroy
      render :text => "success", :status => 200 and return
    else
      render :text => "error", :status => 500 and return
    end
  end
  
  private
    def likes_params
      params.fetch(:like, {}).permit(:tutorial_id, :user_id)
    end
    
    def find_like
      @like = TutorialLike.find_by(tutorial_id: params[:tutorial_id], user_id: params[:user_id])
    end
end

app/helpers/e_sal/comments_helper.rb
module ESal::CommentsHelper
end

app/helpers/e_sal/homes_helper.rb
module ESal::HomesHelper
end

app/helpers/e_sal/original_categories_helper.rb
module ESal::OriginalCategoriesHelper
end

app/helpers/e_sal/photos_helper.rb
module ESal::PhotosHelper
end

app/helpers/e_sal/programming_answers_helper.rb
module ESal::ProgrammingAnswersHelper
end

app/helpers/e_sal/programmings_helper.rb
module ESal::ProgrammingsHelper
end

app/helpers/e_sal/tutorials_helper.rb
module ESal::TutorialsHelper
  def markdown(text)
    unless @markdown
      renderer = Redcarpet::Render::HTML.new(filter_html: true)
      options = {
          autolink: true,
          space_after_headers: true,
          no_intra_emphasis: true,
          fenced_code_blocks: true,
          tables: true,
          hard_wrap: true,
          xhtml: true,
          lax_html_blocks: true,
          strikethrough: true
      }
      @markdown = Redcarpet::Markdown.new(renderer, options)
    end

    @markdown.render(text).html_safe
  end
  
  def persisted_comments(comments)
    comments.reject{ |comment| comment.new_record? }
  end
end

app/views/e_sal/programmings/_form.html.erb
<div class="programming-area">
  <div class="programming-problem-form-wrap">
    <h3><strong>プログラミングの問題作成フォーム</strong></h3>
    <%= form_for([:e_sal, @programming], html: { class: "programming-problem-form form-horizontal" }) do |f| %>
      <% if !f.object.confirmation? %>
        <div class="programming-problem-form__title-field">
          <div class="col-xs-12 form-group ">
            <%= f.label t('.title') %>
            <span style="color: red;"><%= f.label t('.required') %></span>
            <%= f.text_field :title, maxlength: 128, class: "form-control" %>
            <% if @programming.errors.full_messages_for(:title).any? %>
              <div class="field_with_errors">
                <% @programming.errors.full_messages_for(:title).each do |msg| %>
                  <ul>
                    <li><span style="color: red;"><%= msg %></span></li>
                  </ul>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="programming-problem-form__question-desc-field">
          <div class="col-xs-12 form-group">
            <%= f.label t('.question_desc') %>
            <span style="color: red;"><%= f.label t('.required') %></span>
            <%= f.text_area :question_desc, rows: "15", class: "form-control" %>
            <% if @programming.errors.full_messages_for(:question_desc).any? %>
              <div class="field_with_errors">
                <% @programming.errors.full_messages_for(:question_desc).each do |msg| %>
                  <ul>
                    <li><span style="color: red;"><%= msg %></span></li>
                  </ul>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="programming-problem-form__correct-answer-field">
          <div class="col-xs-12 form-group">
            <%= f.label t('.correct_answer') %>
            <span style="color: red;"><%= f.label t('.correct_answer_msg') %></span>
            <%= f.text_area :correct_answer, rows: "5", class: "form-control" %>
          </div>
        </div>
      <% else %>
        <div class="programming-note">
          <i class="programming-note__pin"></i>
          <h2 class="programming-note__title">問題「<%= @programming.title%>」</h2>
          <%= f.hidden_field :title %>
          <div class="programming-note__main-sentence"><%= markdown @programming.question_desc %></div>
          <div class="programming-note__sub-sentence">出題者：<%= @user.user_name %></div>
          <%= f.hidden_field :question_desc %>
          <%= f.hidden_field :correct_answer %>
        </div>
      <% end %>
      <%= f.submit f.object.confirmation? ? "保存する" : "確認する", class: "btn btn-primary programming-problem-form__confirm-button" %>
      <%= f.submit '戻る', class: "btn btn-default programming-problem-form__confirm-button" if f.object.confirmation? %>
      <%= f.hidden_field :confirmed %>
    <% end %>
    <div class="col-xs-2 programming-problem-note-area">
      <div class="fusen">
        <ul>
          <li><h2 style="color: red;">問題を作る際の注意事項</h2></li>
          <li>文字列や数値を出力する問題にしてください</li>
          <li>ファイルやディレクトリ操作を行う問題は避けてください</li>
          <li>問題は保存後直ちに他のユーザに公開されます</li>
          <li>問題に対する回答が作成された時点で編集・削除はできなくなります</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/e_sal/programmings/edit.html.erb
<%= render 'form' %>

app/views/e_sal/programmings/index.html.erb
<div class="programming-area">
  <%= render partial: 'layouts/common_partials/header_stats' %>

    <% selection_item = {"すべて": "all", "下書き": "draft", "回答済み": "answered", "未回答": "not_answered", "自身が出題": "own"} %>
    <%= form_tag e_sal_programmings_path, method: 'get', html: {class: "form-horizontal"} do %>
      <div class="col-xs-3" style="margin-top: 30px; margin-left: 140px;">
        <%= label_tag :status, '抽出条件' %>
        <%= select_tag :status, options_for_select(selection_item, @status), onchange: "this.form.submit();", class: "form-control form-inline" %>
      </div>
    <% end %>
    <div class="col-xs-2" style="margin-top: 55px; margin-left: 235px;">
      <%= link_to new_e_sal_programming_path do %>
        <button type="button" class="btn btn-primary">問題を新規作成する</button>
      <% end %>
    </div>
    <div class="paging"><%= paginate(@programmings) %></div>
    <% unless @programmings.any? %>
      <div class="programming-list__not-found" style="margin: 100px; text-align: center;">
        <h4><%= selection_item.key(@status) %>のものはありません</h4>
      </div>
    <% end %>
    <% @programmings.each do |programming| %>
      <div class="programming-wrap">
        <div class="programming-material">
          <i class="programming-material__pin"></i>
          <div class="programming-material__note programming-material__background">
            <div class="programming-material__title"><%= programming.title %></div>
              <div class="programming-material__body"><%= truncate(markdown(programming.question_desc), length: 80) %></div>
            <%= link_to e_sal_programming_path(programming.id) do %>
              <div class="programming-material__read-more">この問題を見る</div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
<div class="paging"><%= paginate(@programmings) %></div>
</div>

app/views/e_sal/programmings/new.html.erb
<%= render 'form' %>

app/views/e_sal/programmings/show.html.erb
<div class="programming-area">
  <div class="programming-note">
    <i class="programming-note__pin"></i>
    <h2 class="programming-note__title">問題「<%= @programming.title%>」</h2>
    <div class="programming-note__main-sentence"><%= markdown @programming.question_desc %></div>
  </div>
  <div class="programming-button-area" style="text-align: center;">
    <% if @programming_answer.nil? %>
      <%= link_to new_e_sal_programming_programming_answer_path(@programming.id) do %>
        <button type="button" class="btn btn-primary">この問題を解く</button>
      <% end %>
      <% if @programming_own %>
        <%= link_to edit_e_sal_programming_path(@programming.id) do %>
          <button type="button" class="btn btn-primary" style="margin-left: 20px;">この問題を編集する</button>
        <% end %>
        <%= link_to e_sal_programming_path(@programming.id), method: :delete, data: {confirm: "削除してよろしいですか？"} do %>
          <button type="button" class="btn btn-primary" style="margin-left: 20px;">この問題を削除する</button>
        <% end %>
      <% end %>
    <% else %>
      <% if @programming_answer.draft? %>
        <%= link_to edit_e_sal_programming_programming_answer_path(@programming_answer.programming_id, @programming_answer.id) do %>
          <button type="button" class="btn btn-primary">回答を編集する</button>
        <% end %>
      <% elsif @programming_answer.answered? %>
        <%= link_to e_sal_programming_programming_answer_path(@programming_answer.programming_id, @programming_answer.id) do %>
          <button type="button" class="btn btn-primary">回答を確認する</button>
        <% end %>
        <%= link_to list_e_sal_programming_programming_answers_path(@programming.id) do %>
          <button type="button" class="btn btn-primary" style="margin-left: 20px;">他の人の回答を見る</button>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>